# Generated by Django 4.2.20 on 2025-04-27 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='问题描述')),
                ('content', models.TextField(verbose_name='详细描述')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='提问时间')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否解决')),
                ('answer', models.TextField(verbose_name='答案')),
                ('tags', models.ManyToManyField(blank=True, to='QA.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QA', to=settings.AUTH_USER_MODEL, verbose_name='提问用户')),
            ],
            options={
                'verbose_name': '提问',
                'ordering': ['-created_at'],
            },
        ),
    ]
