# Generated by Django 4.2.20 on 2025-04-28 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa', to=settings.AUTH_USER_MODEL, verbose_name='提问用户'),
        ),
    ]
