# Generated by Django 4.2.20 on 2025-04-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_instructor_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('instructor', '讲师权限')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
